### ISSUE TITLE
make the friendly reminder bot's twitter account

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/friendlyreminderbot#18]

**Comment by SohamRatnaparkhi** [comment]
Hey, can you make this twitter bot account and turn it into a developer account and make a file which will have following details:
1. access_token
2. access_token_secret
3. API_key
4. API_secret_key

After doing this, I can try making the `twitter bot` using `tweepy` library. Making the twitter bot requires the 4 details I mentioned earlier. 
Thankyou!

**Comment by ykdojo** [comment]
@SohamRatnaparkhi

I feel like these keys shouldn't be public? Worst case scenario, I wouldn't want it to start spamming random people

**Comment by SohamRatnaparkhi** [comment]
Hmm. that's true @ykdojo . Then how could we proceed with this because without those keys, I guess we won't be able to make a bot. 
Will think for some solutions and if I get any, will write them down here.

**Comment by SohamRatnaparkhi** [comment]
Hey, just an idea struck my head. 
Can we cipher the keys such that only the contributors contributing to this project will  have the idea to decode it. 
So in the file where those keys will be placed, actually the ciphered text will be placed there; and in main.py or some other python file a function can be written to decode the keys and return them to main.py

**Comment by ykdojo** [comment]
No I think the best way for contributors to test it is by creating their own account.
