### ISSUE TITLE
For beginners & advanced coders: add a friendly reminder!

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/friendlyreminderbot#33]
Check [reminders.txt](https://github.com/ykdojo/friendlyreminderbot/blob/main/reminders.txt), and see if there's anything you'd like to add!

If you're not sure how to make your PR, this project might be a good place to practice: https://github.com/firstcontributions/first-contributions

**Comment by shblyng** [comment]
Hey @ykdojo 
I created a pull request to add a couple more mental health reminders. 
Could you check it out?

**Comment by ykdojo** [comment]
@shebuel-oss I gave you a comment!
