### ISSUE TITLE
chore: Add Issue templates

### ISSUE THREAD

**Issue by Pradumnasaraf** [ykdojo/friendlyreminderbot#4]
### Official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for adding issue templates

**Comment by ykdojo** [comment]
@Pradumnasaraf is it necessary to have issue templates?

**Comment by Pradumnasaraf** [comment]
Not necessary, but it helps us in
- Keep a good structure of the issue
- Auto labeling the issue
- Classification

Something similar [to it](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues/new/choose)

**Comment by ykdojo** [comment]
Sure! Did you want to add one?

**Comment by Pradumnasaraf** [comment]
> Sure! Did you want to add one?

Done! :)
