### ISSUE TITLE
decide what the license should be - MIT?

### ISSUE THREAD

**Issue by ykdojo** [ykdojo/friendlyreminderbot#7]

**Comment by victoriacheng15** [comment]
I would say MIT license. Also, maybe this [chooses a license](https://choosealicense.com/) helps you to decide which license to use.

**Comment by ykdojo** [comment]
@victoriacheng15 thank you - let's go with MIT

**Comment by ykdojo** [comment]
@victoriacheng15 any chance you could make a PR for it? no worries if it's too much to ask tho 😅

**Comment by victoriacheng15** [comment]
> @victoriacheng15 any chance you could make a PR for it? no worries if it's too much to ask tho 😅

Yes, I can make the PR for adding license. 😀

**Comment by victoriacheng15** [comment]
Before I add, the `full name` on the license should be `ykdojo`?

**Comment by ykdojo** [comment]
sure, thank you.

or should we include all contributors? not sure

**Comment by victoriacheng15** [comment]
> or should we include all contributors? not sure

Umm, I am not sure. I think it needs to be your name since you are the repo owner and open-sourcing this. And I did some look around repos to find "good first issue" issues today. Most of them tend to have the repo owner name or the organization name.

**Comment by ykdojo** [comment]
ok sounds good! let's use my name for now then
