### ISSUE TITLE
feat: add code of conduct

### ISSUE THREAD

**Issue by SuperAayush** [ykdojo/friendlyreminderbot#9]
Add code of conduct  to define community standards, signal a welcoming and inclusive project, and outline procedures for handling abuse

**Comment by ykdojo** [comment]
would this be in the codebase or somewhere else?

**Comment by victoriacheng15** [comment]
Apparently, GitHub has a template for CoC.

[docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

**Comment by SuperAayush** [comment]
You just have to go to insights of the project and under community standard, you will find a code of conduct section you can add it from there easily or can refer to @victoriacheng15 provided link 😄.

**Comment by ykdojo** [comment]
I checked it, and I thought the template was too long. I'd rather go from the ground up and build it up slowly with the community.. so here it is:

https://github.com/ykdojo/friendlyreminderbot/blob/main/CODE_OF_CONDUCT.md

**Comment by victoriacheng15** [comment]
@ykdojo I think you should close this issue?
